In [1]:
import pandas as pd
import numpy as np
pd.set_option("display.max_rows", None, "display.max_columns", None)
import seaborn as sns
cm = sns.light_palette("green", as_cmap=True)

In [2]:
# Fixme: set up 384 to 96 quadrants.
def quadrants384_to_96(data):
    data = data.copy()
    
    quad1 = []
    for row in np.arange(0, 16, 2): 
        for col in np.arange(0, 23, 2):
            quad1.append(data.values[row, col])


    QUAD1_96 = pd.DataFrame(np.array(quad1).reshape([8, 12])) # 96
    QUAD1_96.columns = np.linspace(1, 12, 12, dtype = np.int)
    QUAD1_96['Row'] = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
    QUAD1_96.set_index(['Row'], inplace = True)

    quad2 = []
    for row in np.arange(0, 16, 2): 
        for col in np.arange(1, 24, 2):
            quad2.append(data.values[row, col])


    QUAD2_96 = pd.DataFrame(np.array(quad2).reshape([8, 12])) # 96
    QUAD2_96.columns = np.linspace(1, 12, 12, dtype = np.int)
    QUAD2_96['Row'] = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
    QUAD2_96.set_index(['Row'], inplace = True)

    quad3 = []
    for row in np.arange(1, 17, 2): 
        for col in np.arange(0, 23, 2):
            quad3.append(data.values[row, col])


    QUAD3_96 = pd.DataFrame(np.array(quad3).reshape([8, 12])) # 96
    QUAD3_96.columns = np.linspace(1, 12, 12, dtype = np.int)
    QUAD3_96['Row'] = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
    QUAD3_96.set_index(['Row'], inplace = True)

    quad4 = []
    for row in np.arange(1, 17, 2): 
        for col in np.arange(1, 24, 2):
            quad4.append(data.values[row, col])


    QUAD4_96 = pd.DataFrame(np.array(quad4).reshape([8, 12])) # 96
    QUAD4_96.columns = np.linspace(1, 12, 12, dtype = np.int)
    QUAD4_96['Row'] = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
    QUAD4_96.set_index(['Row'], inplace = True)

    return QUAD1_96, QUAD2_96, QUAD3_96, QUAD4_96

In [3]:
def printStats(sarsdf, REDdf):
    print('Sars Mean:', sarsdf.values.mean(), '±', sarsdf.values.std())
    print('Sars Max - Min:', sarsdf.values.max() - sarsdf.values.min())
    print(sarsdf.values.max(), sarsdf.values.min())
    print()
    
    print('Cal Red Mean:', REDdf.values.mean(), '±', REDdf.values.std())
    print('Cal Red Max - Min:', REDdf.values.max() - REDdf.values.min())
    print(REDdf.values.max(), REDdf.values.min())
    return

def presentHeatMap(sarsdf, REDdf):
    SARSdf_hm = pd.DataFrame(np.array(sarsdf.values.tolist())).style.background_gradient(cmap='Reds').set_precision(6).highlight_min(axis= None, color='green').highlight_max(axis= None, color='green')
    REDdf_hm = pd.DataFrame(np.array(REDdf.values.tolist())).style.background_gradient(cmap='Reds').set_precision(6).highlight_min(axis= None, color='green').highlight_max(axis= None, color='green')
    display(SARSdf_hm)
    display(REDdf_hm)
    return

def uniformityValidationMethod(file: str, heatmap: bool = False, quadrants384_to_96Method = False):
    
    sarsdf = pd.read_excel(file,
                              sheet_name = 0)
    sarsdf.rename(columns={'Unnamed: 0':'Rows'}, inplace=True)
    sarsdf.set_index('Rows', inplace = True)
    sarsdf = sarsdf[sarsdf['Unnamed: 1'] == 'Cq']
    sarsdf = sarsdf.loc[:, sarsdf.columns != 'Unnamed: 1']  # changed
    sarsdf.columns = sarsdf.columns.astype('int64')
    
    REDdf = pd.read_excel(file,
                              sheet_name = 1)
    REDdf.rename(columns={'Unnamed: 0':'Rows'}, inplace=True)
    REDdf.set_index('Rows', inplace = True)
    REDdf = REDdf[REDdf['Unnamed: 1'] == 'Cq']
    REDdf = REDdf.loc[:, REDdf.columns != 'Unnamed: 1']  # changed
    REDdf.columns = REDdf.columns.astype('int64')
    
    
    if quadrants384_to_96Method == False:
        
        
        printStats(sarsdf, REDdf)
        if heatmap == False:
            display(sarsdf)
            display(REDdf)

        else: 
            presentHeatMap(sarsdf, REDdf)
            
        return
            
    elif quadrants384_to_96Method == True:
        sarsQUAD1_96, sarsQUAD2_96, sarsQUAD3_96, sarsQUAD4_96 = quadrants384_to_96(sarsdf)
        redQUAD1_96, redQUAD2_96, redQUAD3_96, redQUAD4_96 = quadrants384_to_96(REDdf)
        
        for sars, red in zip([sarsQUAD1_96, sarsQUAD2_96, sarsQUAD3_96, sarsQUAD4_96], 
                            [redQUAD1_96, redQUAD2_96, redQUAD3_96, redQUAD4_96]):
            printStats(sars, red)
            if heatmap == False:
                display(sars)
                display(red)

            else: 
                presentHeatMap(sars, red)
        
        
    return

Displaying on 384 plate data

In [7]:
uniformityValidationMethod('AUTO UNIFORM BETH 384 MM 289 BR 38 2_17_21-1 -  Quantification Plate View Results.xlsx',
                          heatmap=False)

Sars Mean: 27.212704899709056 ± 0.10602829712373361
Sars Max - Min: 0.7387851330349022
27.6146765288033 26.8758913957684

Cal Red Mean: 24.738305875013996 ± 0.14350325272770964
Cal Red Max - Min: 1.2732654553969986
25.6619406205032 24.3886751651062

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24
Rows,,,,,,,,,,,,,,,,,,,,,,,,
A,27.2224,27.2536,27.2108,27.1829,27.2983,27.2692,27.3308,27.1934,27.2955,27.1618,27.1555,27.0686,27.2424,27.2658,27.2056,27.1344,27.3746,27.2696,27.2595,27.2372,27.5028,27.3957,27.5059,27.0439
B,27.1205,27.1818,27.3572,27.2056,27.3521,27.1831,27.1854,27.2372,27.3172,27.1216,27.2641,27.0603,27.2521,27.1826,27.303,27.177,27.3228,27.0445,27.2638,27.0804,27.3492,27.3263,27.2843,27.2206
C,27.3383,27.2276,27.2478,27.1178,27.1257,27.1563,27.2924,27.0096,27.1349,27.1261,27.1977,27.0237,27.1044,27.0345,27.0773,27.2397,27.1292,27.1236,27.2749,27.2564,26.9297,27.2776,27.346,27.2903
D,27.2941,27.0811,27.2741,27.2692,27.0999,27.1795,27.0856,27.1495,27.1764,27.0244,27.1624,26.9606,27.4004,27.5424,27.1628,27.2434,27.2255,27.4241,27.2,27.312,27.2459,27.3436,27.2127,27.433
E,27.3463,27.1743,27.2193,27.1866,27.229,27.248,27.1907,27.0048,27.0541,27.249,27.2105,27.0811,27.1299,27.1528,27.2043,27.2584,27.0969,27.1493,27.0865,27.2175,27.0711,27.1395,27.1013,27.2749
F,27.3111,27.2016,27.3792,27.3414,27.1608,27.3284,27.1404,27.2548,27.3136,27.18,27.1857,27.1344,27.2277,27.2259,27.1988,27.261,27.1728,27.2299,27.1555,27.0808,27.153,27.3734,27.3971,27.2085
G,27.2833,27.2069,27.1481,27.0504,27.2544,27.1564,27.067,27.0546,27.2588,27.0528,27.1178,27.047,27.018,27.0425,26.9522,27.0927,27.2137,27.097,27.0172,27.0563,27.1754,27.1783,27.245,27.132
H,27.0839,27.1598,27.3142,27.2761,27.203,27.1605,27.3394,27.1922,27.2488,27.2553,27.1443,27.1725,27.1066,27.1623,27.1257,27.2443,27.235,27.2124,27.1198,27.1613,27.2093,27.1314,27.2347,27.2097
I,27.3343,27.2288,27.3831,27.0827,27.0279,27.1695,27.0934,27.0865,27.0833,27.1179,27.0884,27.1246,27.0191,27.2486,26.9854,27.152,27.1985,27.0749,27.1139,27.2434,27.1831,27.2398,27.2248,27.2264
J,27.2504,27.1704,27.1687,27.1564,27.1655,27.2101,27.3116,27.2681,27.3529,27.245,27.1908,27.2749,27.2406,27.2969,27.31,27.3256,27.3001,27.2987,27.2131,27.13,27.1664,27.1754,27.1785,27.2683
K,27.3368,27.307,27.2928,26.8759,27.1963,27.2394,27.1585,27.2557,27.0662,27.1172,27.0452,27.106,27.2516,27.1973,27.0938,27.1567,27.151,27.2687,27.1514,27.148,27.2147,27.2877,27.2208,27.1593
L,27.3188,27.2022,27.3781,27.1785,27.2668,27.1034,27.1789,27.2364,27.2017,27.1712,27.189,27.1932,27.2004,27.384,27.071,27.4691,27.2356,27.2478,27.2551,27.326,27.3201,27.6147,27.1421,27.1598
M,27.2865,27.3221,27.2014,27.0617,27.1545,27.0523,27.1393,27.2726,27.2542,27.1251,27.1113,27.2754,27.1321,27.0612,27.1569,27.2454,27.3591,27.2463,26.9793,27.1379,27.1095,27.3152,27.3219,27.2592
N,27.216,27.392,27.3133,27.1373,27.2203,27.2394,27.1059,27.226,27.1515,27.0689,27.292,27.3395,27.2919,27.2796,27.1699,27.4915,27.3858,27.404,27.0678,27.2115,27.2545,27.2838,27.2787,27.2813
O,27.2779,27.1569,27.3394,27.379,27.2138,27.1816,27.1581,27.3111,27.3121,27.207,27.2106,27.1704,27.1923,27.1883,27.3169,27.2442,27.1674,27.1169,27.204,27.266,27.2625,27.2721,27.1981,27.3398
P,27.2816,27.2038,27.4154,27.4122,27.2935,27.324,27.2049,27.1991,27.2939,27.2931,27.2525,27.3226,27.2579,27.1955,27.4095,27.3351,27.4543,27.277,27.3147,27.3284,27.4798,27.3129,27.3405,26.9979

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24
Rows,,,,,,,,,,,,,,,,,,,,,,,,
A,24.6899,24.6144,24.7464,25.1746,24.6893,24.687,24.7872,24.7151,24.8243,24.612,24.7919,24.8552,25.0131,24.8877,24.5833,24.659,24.952,25.0028,24.8267,24.8189,24.9782,24.9162,25.0323,24.5448
B,24.5924,24.5999,24.6889,24.5799,24.6867,24.6408,24.7071,24.5292,24.5979,24.5183,24.5155,24.5335,24.5731,24.5751,24.6534,24.4931,24.6841,24.5569,24.5772,24.6952,24.7162,24.6847,24.6336,24.7709
C,24.7109,24.7568,24.81,24.6485,24.788,24.6913,24.8634,25.0717,24.5948,24.9172,24.7909,24.5917,24.722,24.6774,24.5288,24.9163,24.7787,24.7632,24.8013,24.8101,24.644,24.794,24.9079,24.7785
D,24.8969,24.5625,24.6561,24.6627,24.552,24.5986,24.5392,24.58,24.5756,24.8098,25.0338,24.5818,25.0179,24.9858,24.5256,24.7715,24.8708,24.6918,24.7357,24.8541,24.8406,24.7578,24.7282,24.9516
E,24.8286,24.6997,24.7429,24.835,25.0238,24.814,25.0614,24.7553,24.6217,24.8191,24.7196,24.7354,24.8962,24.7564,24.7009,24.748,24.6122,24.7466,24.6058,24.6983,24.6911,24.7198,24.71,24.7646
F,24.7308,24.5765,24.5935,24.7861,24.6599,24.6456,24.8326,24.7409,24.8636,24.7807,24.7522,24.7878,24.8058,24.7927,24.695,24.7376,24.5994,24.626,24.5641,24.4594,24.5186,24.8511,24.7109,24.6539
G,24.7586,24.5345,24.6311,24.5662,24.8332,24.7731,24.7251,24.6271,24.8745,24.7845,24.8447,24.8226,24.8357,24.9431,24.8961,24.8584,24.7843,24.6886,24.6296,24.6725,24.7109,24.7483,24.6617,24.6071
H,24.7583,24.564,24.7128,24.598,24.5911,24.6683,24.8145,24.5406,24.8949,24.7846,24.855,25.0162,24.8837,25.2025,25.3437,25.044,24.7228,24.6093,24.7688,24.8595,24.8993,24.6271,24.6035,24.6154
I,24.8187,24.8024,24.9176,24.6416,24.758,24.675,24.8213,24.7035,24.6366,24.873,25.012,24.7879,25.0084,25.1001,24.7737,24.847,24.9838,24.6366,24.7369,24.8642,24.7578,24.7157,24.6726,24.6612
J,24.7822,24.5696,24.6879,24.5923,24.7202,24.6199,24.7158,24.8764,25.0619,24.7351,25.0172,24.9641,24.8808,24.9036,25.0105,24.8278,24.7359,24.6444,24.8055,24.6633,24.5283,24.519,24.53,24.5603
K,24.7999,24.7781,24.8089,25.1149,24.7066,24.7467,24.6654,24.7925,24.5335,24.6327,24.5111,24.624,24.865,24.8987,24.6721,24.6767,24.6624,24.7538,24.7047,24.6375,24.7625,24.7875,24.7967,24.6322
L,24.9044,24.62,24.5404,24.5495,24.7475,24.6109,24.5504,24.5967,24.6489,24.6661,24.7915,24.7451,24.5856,24.814,24.4873,24.785,24.7132,24.6787,24.646,24.7161,24.9304,24.8198,24.5182,24.6688
M,24.8424,24.844,24.7427,25.6619,24.6489,25.0658,24.8663,24.9166,24.6152,24.6256,24.6667,24.6822,24.5605,24.5666,24.8012,24.7983,24.7818,24.7915,24.6502,24.6136,24.5916,24.6805,24.7812,24.6569
N,24.68,24.7214,24.7787,24.5683,24.8219,24.7123,24.5279,24.7053,24.7203,24.3887,24.8726,24.7364,24.8064,24.7384,24.7442,24.8016,24.8333,24.7415,24.7348,24.6178,24.5986,24.7516,24.5767,24.7609
O,24.8169,24.6942,24.7123,24.8095,24.7177,24.5691,24.6614,24.7948,24.8068,24.8292,24.7376,24.7884,24.8793,24.7142,24.8372,24.7256,24.7527,24.6059,24.6909,24.6817,24.755,24.6717,24.6204,24.668
P,24.6862,24.5626,24.7856,24.7833,24.7109,24.7472,24.7223,24.6751,24.7103,24.7715,24.748,24.7186,24.8239,24.7607,24.8713,24.6568,24.9961,24.7323,24.7095,24.6938,24.6971,24.7105,24.5931,24.451

Displaying 384 data in four 96 quadrants.

In [6]:
uniformityValidationMethod('AUTO UNIFORM BETH 384 MM 289 BR 38 2_17_21-1 -  Quantification Plate View Results.xlsx',
                          heatmap=False, quadrants384_to_96Method=True)

Sars Mean: 27.192359062744575 ± 0.11065576370550376
Sars Max - Min: 0.5762217026266008
27.5058751733482 26.9296534707216

Cal Red Mean: 24.76226886149708 ± 0.1194339312844178
Cal Red Max - Min: 0.5502840379411005
25.0613682086252 24.5110841706841

,1,2,3,4,5,6,7,8,9,10,11,12
Row,,,,,,,,,,,,
A,27.222445,27.210789,27.298321,27.330818,27.295546,27.155498,27.242425,27.205569,27.374624,27.259477,27.502764,27.505875
B,27.338326,27.247800,27.125743,27.292370,27.134886,27.197696,27.104409,27.077299,27.129220,27.274884,26.929653,27.346035
C,27.346266,27.219255,27.228955,27.190667,27.054119,27.210490,27.129898,27.204336,27.096855,27.086471,27.071074,27.101347
D,27.283313,27.148071,27.254415,27.066976,27.258819,27.117783,27.017956,26.952225,27.213667,27.017244,27.175367,27.244953
E,27.334329,27.383091,27.027890,27.093444,27.083330,27.088414,27.019095,26.985351,27.198544,27.113941,27.183142,27.224832
F,27.336796,27.292766,27.196321,27.158544,27.066172,27.045155,27.251618,27.093849,27.151034,27.151448,27.214665,27.220767
G,27.286488,27.201383,27.154463,27.139346,27.254243,27.111257,27.132076,27.156948,27.359059,26.979288,27.109461,27.321874
H,27.277938,27.339414,27.213846,27.158063,27.312063,27.210631,27.192289,27.316863,27.167413,27.203976,27.262499,27.198058

,1,2,3,4,5,6,7,8,9,10,11,12
Row,,,,,,,,,,,,
A,24.689946,24.746395,24.689306,24.787157,24.824313,24.791931,25.013099,24.583252,24.951960,24.826712,24.978174,25.032315
B,24.710864,24.809979,24.787986,24.863370,24.594843,24.790938,24.722008,24.528845,24.778655,24.801309,24.643977,24.907872
C,24.828562,24.742865,25.023819,25.061368,24.621668,24.719584,24.896206,24.700926,24.612157,24.605826,24.691058,24.709971
D,24.758586,24.631145,24.833152,24.725110,24.874532,24.844714,24.835698,24.896119,24.784278,24.629638,24.710918,24.661697
E,24.818668,24.917632,24.757980,24.821275,24.636618,25.011977,25.008408,24.773745,24.983829,24.736878,24.757790,24.672554
F,24.799863,24.808910,24.706633,24.665443,24.533470,24.511084,24.865029,24.672148,24.662384,24.704674,24.762506,24.796662
G,24.842354,24.742710,24.648851,24.866342,24.615211,24.666712,24.560479,24.801246,24.781820,24.650224,24.591583,24.781223
H,24.816920,24.712309,24.717650,24.661439,24.806803,24.737593,24.879262,24.837171,24.752652,24.690945,24.754976,24.620375

Sars Mean: 27.17691549336853 ± 0.09405784183069794
Sars Max - Min: 0.519786657292002
27.3956780530604 26.8758913957684

Cal Red Mean: 24.76522758762361 ± 0.1569570236779221
Cal Red Max - Min: 1.1274043844336
25.6619406205032 24.5345362360696

,1,2,3,4,5,6,7,8,9,10,11,12
Row,,,,,,,,,,,,
A,27.253641,27.182863,27.269195,27.193434,27.161815,27.068585,27.265842,27.134425,27.269589,27.237204,27.395678,27.043904
B,27.227558,27.117755,27.156256,27.009584,27.126133,27.023655,27.034500,27.239728,27.123572,27.256450,27.277562,27.290316
C,27.174270,27.186556,27.247999,27.004827,27.248980,27.081112,27.152794,27.258445,27.149259,27.217492,27.139460,27.274919
D,27.206928,27.050373,27.156404,27.054589,27.052808,27.047001,27.042526,27.092659,27.097026,27.056308,27.178300,27.132011
E,27.228759,27.082660,27.169550,27.086461,27.117857,27.124579,27.248597,27.151985,27.074853,27.243405,27.239810,27.226423
F,27.307002,26.875891,27.239426,27.255736,27.117184,27.105975,27.197309,27.156699,27.268748,27.147966,27.287711,27.159269
G,27.322070,27.061738,27.052284,27.272562,27.125103,27.275370,27.061154,27.245414,27.246261,27.137933,27.315236,27.259189
H,27.156941,27.379009,27.181630,27.311069,27.206983,27.170390,27.188282,27.244240,27.116883,27.266045,27.272131,27.339829

,1,2,3,4,5,6,7,8,9,10,11,12
Row,,,,,,,,,,,,
A,24.614352,25.174558,24.686987,24.715131,24.612014,24.855200,24.887722,24.659027,25.002757,24.818921,24.916229,24.544841
B,24.756765,24.648507,24.691316,25.071727,24.917183,24.591652,24.677370,24.916332,24.763233,24.810065,24.793966,24.778483
C,24.699668,24.834963,24.814000,24.755260,24.819079,24.735391,24.756401,24.748015,24.746598,24.698308,24.719815,24.764556
D,24.534536,24.566247,24.773115,24.627112,24.784455,24.822633,24.943079,24.858354,24.688580,24.672525,24.748255,24.607130
E,24.802399,24.641618,24.674994,24.703528,24.872999,24.787902,25.100061,24.847017,24.636648,24.864234,24.715660,24.661206
F,24.778117,25.114922,24.746678,24.792493,24.632728,24.624026,24.898655,24.676707,24.753813,24.637521,24.787545,24.632180
G,24.844029,25.661941,25.065790,24.916631,24.625598,24.682167,24.566649,24.798252,24.791542,24.613607,24.680506,24.656859
H,24.694205,24.809538,24.569117,24.794839,24.829162,24.788414,24.714193,24.725554,24.605872,24.681655,24.671678,24.667987

Sars Mean: 27.24399966547806 ± 0.08954934075169303
Sars Max - Min: 0.41197165362249777
27.4797549617902 27.0677833081677

Cal Red Mean: 24.72982352910688 ± 0.14848764421353486
Cal Red Max - Min: 0.856319671546597
25.3436665672877 24.4873468957411

,1,2,3,4,5,6,7,8,9,10,11,12
Row,,,,,,,,,,,,
A,27.120521,27.357233,27.352094,27.185434,27.317211,27.264069,27.252083,27.302990,27.322796,27.263796,27.349213,27.284277
B,27.294083,27.274118,27.099907,27.085643,27.176433,27.162389,27.400386,27.162755,27.225522,27.199981,27.245876,27.212687
C,27.311099,27.379189,27.160841,27.140381,27.313550,27.185650,27.227726,27.198799,27.172830,27.155503,27.153034,27.397096
D,27.083853,27.314194,27.203015,27.339412,27.248766,27.144281,27.106551,27.125670,27.235030,27.119794,27.209329,27.234718
E,27.250373,27.168668,27.165460,27.311619,27.352933,27.190761,27.240631,27.310046,27.300078,27.213150,27.166387,27.178476
F,27.318775,27.378111,27.266782,27.178887,27.201735,27.188990,27.200419,27.070980,27.235635,27.255098,27.320086,27.142051
G,27.216007,27.313276,27.220320,27.105909,27.151486,27.292024,27.291913,27.169929,27.385790,27.067783,27.254463,27.278651
H,27.281637,27.415399,27.293502,27.204926,27.293875,27.252475,27.257946,27.409452,27.454274,27.314730,27.479755,27.340510

,1,2,3,4,5,6,7,8,9,10,11,12
Row,,,,,,,,,,,,
A,24.592365,24.688864,24.686701,24.707060,24.597876,24.515539,24.573090,24.653416,24.684133,24.577216,24.716233,24.633588
B,24.896894,24.656130,24.551967,24.539240,24.575558,25.033755,25.017940,24.525624,24.870751,24.735728,24.840601,24.728152
C,24.730835,24.593531,24.659876,24.832631,24.863613,24.752202,24.805799,24.695028,24.599450,24.564093,24.518609,24.710935
D,24.758286,24.712839,24.591070,24.814523,24.894914,24.854990,24.883685,25.343667,24.722831,24.768787,24.899302,24.603495
E,24.782178,24.687857,24.720222,24.715769,25.061939,25.017174,24.880823,25.010464,24.735927,24.805464,24.528319,24.530023
F,24.904432,24.540408,24.747525,24.550409,24.648917,24.791487,24.585646,24.487347,24.713175,24.646006,24.930363,24.518171
G,24.679984,24.778661,24.821862,24.527873,24.720264,24.872620,24.806370,24.744243,24.833323,24.734771,24.598624,24.576705
H,24.686185,24.785608,24.710935,24.722260,24.710317,24.748030,24.823921,24.871316,24.996078,24.709482,24.697102,24.593072

Sars Mean: 27.23754537724517 ± 0.11209858476770986
Sars Max - Min: 0.6540972561183018
27.6146765288033 26.960579272685

Cal Red Mean: 24.69590352182838 ± 0.13511206232966202
Cal Red Max - Min: 0.8138683641833993
25.2025435292896 24.3886751651062

,1,2,3,4,5,6,7,8,9,10,11,12
Row,,,,,,,,,,,,
A,27.181800,27.205583,27.183149,27.237235,27.121554,27.060344,27.182634,27.176972,27.044452,27.080402,27.326251,27.220633
B,27.081135,27.269152,27.179547,27.149495,27.024404,26.960579,27.542373,27.243438,27.424070,27.311988,27.343582,27.432967
C,27.201600,27.341373,27.328418,27.254788,27.179988,27.134448,27.225901,27.261011,27.229904,27.080849,27.373401,27.208523
D,27.159798,27.276081,27.160473,27.192230,27.255286,27.172539,27.162295,27.244260,27.212411,27.161300,27.131402,27.209715
E,27.170357,27.156402,27.210053,27.268105,27.245023,27.274946,27.296857,27.325647,27.298688,27.130008,27.175448,27.268285
F,27.202237,27.178460,27.103395,27.236367,27.171189,27.193155,27.384049,27.469148,27.247766,27.326027,27.614677,27.159822
G,27.392025,27.137330,27.239427,27.225958,27.068884,27.339499,27.279609,27.491460,27.403975,27.211521,27.283802,27.281310
H,27.203844,27.412236,27.324032,27.199135,27.293122,27.322582,27.195487,27.335083,27.276993,27.328390,27.312892,26.997916

,1,2,3,4,5,6,7,8,9,10,11,12
Row,,,,,,,,,,,,
A,24.599934,24.579908,24.640821,24.529242,24.518272,24.533452,24.575053,24.493136,24.556919,24.695235,24.684729,24.770926
B,24.562452,24.662720,24.598559,24.580016,24.809836,24.581759,24.985817,24.771457,24.691752,24.854057,24.757765,24.951576
C,24.576465,24.786114,24.645565,24.740872,24.780668,24.787754,24.792697,24.737616,24.626015,24.459356,24.851074,24.653853
D,24.564006,24.598008,24.668303,24.540638,24.784585,25.016216,25.202544,25.043968,24.609310,24.859504,24.627081,24.615417
E,24.569612,24.592253,24.619850,24.876399,24.735067,24.964129,24.903632,24.827792,24.644394,24.663257,24.518965,24.560281
F,24.619992,24.549488,24.610855,24.596684,24.666102,24.745075,24.814007,24.785037,24.678730,24.716058,24.819795,24.668767
G,24.721358,24.568288,24.712288,24.705309,24.388675,24.736389,24.738395,24.801573,24.741462,24.617846,24.751647,24.760870
H,24.562594,24.783264,24.747239,24.675134,24.771506,24.718576,24.760663,24.656797,24.732350,24.693752,24.710499,24.451019